---
- block:

  - name: Install crda
    pacman:
      name: crda

  - name: Install the wireless regulatory domain configuration file
    copy:
      src: wireless-regdom
      dest: /etc/conf.d/wireless-regdom
      mode: 0644
    notify: Set the wireless regulatory domain

  become: true
