---
- name: Install borg
  dnf:
    name: borgbackup
    state: present
  become: true

- include_tasks: configure-user.yml
  loop: '{{ borg_backup_users }}'
  loop_control:
    loop_var: borg_backup_user
