---
- block:

  - name: Install nginx
    pacman:
      name: nginx

  - name: Let nginx access media files (esp. torrents)
    user:
      name: http
      groups:
        - media
      create_home: false

  - name: Install htpasswd file for syncthing.jerebear.name
    htpasswd:
      name: admin
      password: '{{ syncthing_password }}'
      path: /etc/nginx/{{ 'syncthing.jerebear.name' | systemd_escape }}.htpasswd
      owner: root
      group: http
      mode: 0640
    when: syncthing_password is defined

  - name: Install htpasswd file for transmission.jerebear.name
    htpasswd:
      name: admin
      password: '{{ transmission_password }}'
      path: >-
        /etc/nginx/{{ 'transmission.jerebear.name' | systemd_escape }}.htpasswd
      owner: root
      group: http
      mode: 0640
    when: transmission_password is defined

  - name: Install nginx configuration file
    template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    notify: Reload nginx

  - name: Create directory for SSL certificates
    file:
      path: /etc/nginx/ssl
      state: directory
      mode: 0700

  - include_tasks: install-domain-certs.yml
    loop: '{{ nginx_ssl_domains }}'
    loop_control:
      loop_var: nginx_ssl_domain

  - include_tasks: uninstall-domain-certs.yml

  # From ansible-doc: The [copy] module recursively copy facility does not scale
  # to lots (>hundreds) of files. For alternative, see [synchronize] module,
  # which is a wrapper around `rsync'.
  - name: Install files for static websites
    copy:
      src: '{{ item }}'
      dest: /usr/share/nginx/
      owner: root
      group: root
      mode: 0644
      directory_mode: 0755
    loop:
      - transmission.jerebear.name
      - www.backtobasicsreading.com
      - www.jerebear.name

  - name: Delete outdated files
    file:
      path: '{{ item }}'
      state: absent
    loop:
      - >-
        /etc/nginx/{{
          'transmission.ichimonji10.name' | systemd_escape
        }}.htpasswd
      - >-
        /etc/nginx/{{
          'packages.ichimonji10.name/arch-linux/ichi-private' | systemd_escape
        }}.htpasswd
      - >-
        /etc/nginx/{{
          'packages.jerebear.name/arch-linux/ichi-private' | systemd_escape
        }}.htpasswd
      - /usr/share/nginx/transmission.ichimonji10.name
      - /usr/share/nginx/www.ichimonji10.name

  - name: Start and enable nginx
    systemd:
      name: nginx.service
      state: started
      enabled: true
      daemon_reload: true

  become: true
