---
- block:

  - name: Create directories named by ~/.vimrc
    file:
      path: "{{ item }}"
      state: directory
      mode: 0700
    loop:
      - "{{ user_jaudet_home }}/.cache/custom-ctags"
      - "{{ user_jaudet_home }}/.vim/autoload"
      - "{{ user_jaudet_home }}/.vim/undo"
      - "{{ user_jaudet_home }}/code"

  - name: Install vim-plug
    ansible.builtin.get_url:
      url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      dest: '{{ user_jaudet_home }}/.vim/autoload/plug.vim'
      mode: '0600'

  - name: Install ~/.vimrc
    copy:
      src: vimrc
      dest: "{{ user_jaudet_home }}/.vimrc"
      mode: 0600

  become: true
  become_user: jaudet
