---
- name: Assert required variables have been set
  assert:
    that: syncthing_usernames is defined

- name: Install syncthing
  package:
    name: syncthing
  become: true

- include_tasks: syncthing-for-user.yml
  loop: '{{ syncthing_usernames }}'
  loop_control:
    loop_var: syncthing_username
