---
# network branches & leaves ########################################################################

- hosts: network_branches
  roles:
    - networking-nm-branch
    - nftables-branch

- hosts: network_leaves
  roles:
    - networking-nm-leaf
    - nftables-leaf

# disorganized, should reorganize to match inventory ###############################################

# Make custom packages available to subsequent roles.
- hosts: webservers
  roles:
    - custom-repo  # TODO: drop
    - nginx  # Make sure to install SSL certificates.

- hosts: all
  roles:
    - crda
    - dynamic-dns
    - essential-apps
    - lm-sensors
    - locale
    - pacman-conf
    - smartd
    - time
    - ucode
    - user-ichimonji10

- hosts: coreboot_hosts
  roles:
    - coreboot

- hosts: uefi_hosts
  roles:
    - uefi

- hosts: workstations
  roles:
    - borg-backup-users
    - dev-env
    - workstation

- hosts: syncthing_hosts
  roles:
    - syncthing

- hosts: vm_hosts
  roles:
    - dockerd
    - libvirtd

- hosts: btrfs_hosts
  roles:
    - btrfs-balance
    - btrfs-scrub
    - btrfs-subvolume

- hosts: servers
  roles:
    - sshd

- hosts: apc_hosts
  roles:
    - apcupsd

- hosts: bittorrent_hosts
  roles:
    - transmission

- hosts: mnemosyne_hosts
  roles:
    - mnemosyne

- hosts: webservers
  roles:
    - airsonic
    - borg-backup-system
