---
- block:

  - name: Install btrfs-progs
    pacman:
      name: btrfs-progs
      state: present

  - name: Install units for btrfs balances
    copy:
      src: '{{ item }}'
      dest: /etc/systemd/system/{{ item }}
      mode: 0644
    loop:
      - btrfs-balance@.service
      - btrfs-balance@.timer

  - name: Start and enable timer for starting btrfs balances
    systemd:
      name: btrfs-balance@{{ item | systemd_escape }}.timer
      state: started
      enabled: true
      daemon_reload: true
    loop: '{{ btrfs_paths }}'

  become: true
