---
- block:

  - name: Install NetworkManager and NetworkManager plugins
    pacman:
      name:
        - networkmanager
        - networkmanager-openvpn
        - systemd-resolvconf  # used by wg-quick
        - wireguard-tools
      state: present

  - name: Configure NetworkManager
    copy:
      src: dns.conf
      dest: /etc/NetworkManager/conf.d/
      mode: 0644
    notify: Reload NetworkManager

  - name: Start and enable NetworkManager and dependent services
    systemd:
      name: '{{ item }}'
      state: started
      enabled: true
    loop:
      - systemd-resolved.service
      - NetworkManager.service

  - name: Install OpenVPN connection profiles
    copy:
      src: '{{ item }}'
      dest: /etc/NetworkManager/system-connections/
      mode: 0600
    notify: Reload NetworkManager
    loop:
      - PHX2.ovpn
      - RDU2.ovpn

  become: true
