---
- name: Check whether pkgfile is installed
  command: pacman -Qi pkgfile
  changed_when: false
  failed_when: false
  register: result

- block:

  # Clean-up from a prior version of this role.
  - name: Stop and disable pkgfile-update.timer
    systemd:
      name: pkgfile-update.timer
      state: stopped
      enabled: false
      daemon_reload: true
    when: result.rc == 0

  - name: Uninstall pkgfile
    pacman:
      name: pkgfile
      state: absent

  become: true
