---
- block:

  - name: Create ~/.config/tmuxp/
    file:
      path: '{{ user_ichimonji10_home }}/.config/tmuxp/'
      state: directory
      mode: 0700

  - name: Install tmuxp config files
    copy:
      src: config_tmuxp/
      dest: '{{ user_ichimonji10_home }}/.config/tmuxp/'
      mode: 0700

  become: true
  become_user: ichimonji10
