---
- block:

  - name: Install config files
    copy:
      src: 50-wired.network
      dest: /etc/systemd/network/
      mode: 0644

  - name: Start and enable network management tools
    systemd:
      name: '{{ item }}'
      state: started
      enabled: true
    loop:
      - systemd-networkd.service
      - systemd-resolved.service

  become: true
