---
- block:

  - name: Install config files
    copy:
      src: 50-wired.network
      dest: /etc/systemd/network/
      mode: 0644

  - name: Install unit override file
    copy:
      src: override.conf
      dest: /etc/systemd/system/systemd-networkd-wait-online.service.d/
      mode: 0644
    register: result

  - name: Reload systemd
    systemd:
      daemon_reload: true
    when: result is changed

  - name: Start and enable network management tools
    systemd:
      name: '{{ item }}'
      state: started
      enabled: true
    loop:
      - systemd-networkd.service
      - systemd-resolved.service

  become: true
