---
- include_tasks: install.yml
  when: networking_nm_leaf_install

- include_tasks: install-gui.yml
  when:
    - networking_nm_leaf_install
    - networking_nm_leaf_has_gui

- include_tasks: uninstall.yml
  when: not networking_nm_leaf_install
