#!/usr/bin/env bash
#
# For each device, start a short SMART self-test.
set -euo pipefail

# We could iterate through device files like produced by $(ls /dev/sd[a-z]), but many of those files
# don't refer to functioning drives. `smartctl --scan` somehow seems to be able to throw away the
# junk drive entries.
while read -r device extra; do
    smartctl -t short "${device}"
done < <(smartctl --scan)
