---
- block:

  - name: Create ~/.ssh/keys
    file:
      path: '{{ user_ichimonji10_home }}/.ssh/keys'
      state: directory
      mode: 0700

  - name: Install public SSH key on servers
    copy:
      dest: '{{ user_ichimonji10_home }}/.ssh/authorized_keys'
      content: '{{ ssh_keypairs[inventory_hostname]["ichimonji10"]["public"] }}'
      mode: 0600
    when: "'servers' in group_names"

  - name: Uninstall public SSH key from non-servers
    file:
      dest: '{{ user_ichimonji10_home }}/.ssh/authorized_keys'
      state: absent
    when: "'servers' not in group_names"

  - name: Install private SSH keys on network leaves
    copy:
      dest: '{{ user_ichimonji10_home }}/.ssh/keys/{{ item }}'
      content: '{{ ssh_keypairs[item]["ichimonji10"]["private"] }}'
      mode: 0600
    loop:
      - amelanchier.jerebear.name
      - aronia.jerebear.name
      - pine.jerebear.name
    when: "'network_leaves' in group_names"

  - name: Uninstall outdated SSH keys
    file:
      dest: '{{ user_ichimonji10_home }}/.ssh/{{ item }}'
      state: absent
    loop:
      - amelanchier.ichimonji10.name
      - amelanchier.jerebear.name
      - aronia.ichimonji10.name
      - aronia.jerebear.name
      - beech.ichimonji10.name
      - pine.ichimonji10.name
      - pine.jerebear.name
      - tupelo.ichimonji10.name

  become: true
  become_user: ichimonji10
