---
- block:

  - name: Create directories named by ~/.vimrc
    file:
      path: "{{ item }}"
      state: directory
      mode: 0700
    loop:
      - "{{ user_ichimonji10_home }}/.cache/custom-ctags"
      - "{{ user_ichimonji10_home }}/.vim/undo"
      - "{{ user_ichimonji10_home }}/code"

  - name: Install ~/.vimrc
    template:
      src: vimrc
      dest: "{{ user_ichimonji10_home }}/.vimrc"
      mode: 0600

  become: true
  become_user: ichimonji10
