---
- block:

  - name: Install openssh-server
    package:
      name: openssh-server
      state: present

  - name: Install sshd configuration file
    copy:
      src: 50-jaudet.conf
      dest: /etc/ssh/sshd_config.d/
      mode: 0600
    notify: Reload sshd

  - name: Start and enable sshd
    systemd:
      name: sshd.service
      state: started
      enabled: true
      daemon_reload: true

  become: true
