---
- block:

  - name: Install configuration file
    copy:
      src: 50-wired.network
      dest: /etc/systemd/network/

  - name: Start and enable systemd-networkd
    systemd:
      name: systemd-networkd
      state: started
      enabled: true

  become: true
