---
- block:

  - name: Create directory for systemd unit
    file:
      path: "{{ user_ichimonji10_home }}/.config/systemd/user"
      state: directory

  - name: Install sphinx-rebuild.service
    template:
      src: sphinx-rebuild.service
      dest: "{{ user_ichimonji10_home }}/.config/systemd/user/"

  - name: Start and enable sphinx-rebuild.service
    systemd:
      name: sphinx-rebuild.service
      state: started
      enabled: true
      daemon_reload: true
      scope: user

  become: true
  become_user: ichimonji10
