---
- block:

  - name: Create {{ btrfs_subvolume.path }}/../snapshots/{{ btrfs_subvolume.path | basename }}
    file:
      path: '{{ btrfs_subvolume.path }}/../snapshots/{{ btrfs_subvolume.path | basename }}'
      state: directory
      mode: 0755

  - name: Start and enable btrfs-subvolume-snapshot@{{ btrfs_subvolume.escaped_path }}.timer
    systemd:
      name: btrfs-subvolume-snapshot@{{ btrfs_subvolume.escaped_path }}.timer
      state: started
      enabled: true
      daemon_reload: true

  become: true
